version: '3'

services: 
  hackideas:
    container_name: hackideas
    build: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '1234:1234'
    environment:
      - NODE_ENV=development